// Array (Relação de dados indexados)
/* tambem conhecido como
vetores ou matrizes.

Finalidade deste recurso é armazenar 
uma série de dados num mesmo espaço de mémoria. */

// Exemplos
let alunos = ["Raphael", "Thiago", "Kaiky"];

console.log(alunos);
// Acessando o dado pelo índice
console.log(alunos[1]);
console.log(alunos[0]);

/* Mini- exercício:
-Crie um array com uma lista de 5 comidas 
que você mais gosta
-Exiba no console uma mensagem dizendo qual
 o nome da terceira e da última comida */



let comidas = ["japonesa", "italiana", "mineira", "churrasco", "arabes"];
console.log(comidas);
console.log(`Minhas comidas favoritas são a ${comidas[2]} e a ${comidas[4]}`);


console.log("----------");

// Matriz de 2 dimensões

let tecnologias = [
        ["HTML", "CSS", "JS"],
        ["PHP", "Node", "Java","SQL"],
        ["Figma", "Photoshop"]
];

console.log(tecnologias);
console.log(tecnologias[0][2]);   // JS
console.log(tecnologia[1][1]);    // Node
console.log(tecnologias[2][1]);   //photoshop










